#!/usr/bin/env bash

set -x

rm -f sparql
make sparql

ctrl=$(buildah from $1)

buildah run "$ctrl" -- dnf install -y rasqal-devel redland-devel raptor2-devel
buildah run "$ctrl" -- dnf install -y boost-system boost-coroutine
buildah add "$ctrl" sparql /usr/local/bin/sparql
buildah add "$ctrl" challenges.db /usr/local/kb/kb.db

buildah config --workingdir /usr/local/kb/ "$ctrl"
buildah config --cmd '/usr/local/bin/sparql 8089 sqlite kb.db' "$ctrl"
buildah config --port 8089 "$ctrl"

buildah commit "$ctrl" $2

