
name: Publish docker images

on:
  pull_request:

permissions:
  contents: read

jobs:

  container-push:

    name: Container push
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: version
        run: echo VERSION=sha-$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT

      - name: Install packages
        run: sudo apt update &&
            sudo apt install redland-utils librdf-storage-sqlite

      - name: Assemble RDF data
        run: make curate

